#!/usr/bin/env bash
set -e

# =========================================================
# Project Runtime Bootstrap
# Creates:
#   - .mise.toml
#   - .envrc
# =========================================================

PROJECT_DIR="$(pwd)"

echo "=== Project Runtime Init ==="
echo "Project: $PROJECT_DIR"
echo

# ---------------------------------------------------------
# Helpers
# ---------------------------------------------------------
info()  { echo "[INFO] $1"; }
warn()  { echo "[WARN] $1"; }
ok()    { echo "[OK]   $1"; }

# ---------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------
command -v mise >/dev/null 2>&1 || {
  warn "mise not found. Install mise first."
  exit 1
}

command -v direnv >/dev/null 2>&1 || {
  warn "direnv not found. Install direnv first."
  exit 1
}

# ---------------------------------------------------------
# .mise.toml
# ---------------------------------------------------------
if [ -f ".mise.toml" ]; then
  warn ".mise.toml already exists. Skipping."
else
  info "Creating .mise.toml"

  cat > .mise.toml <<'EOF'
# =========================================================
# Project Runtime Contract
# Generated by init-project.sh
# =========================================================

[tools]
node = "20.11.1"
pnpm = "9.1.2"

# Uncomment as needed
# python = "3.12.2"
# go     = "1.22.1"
# rust   = "1.77.1"

[env]
NODE_ENV = "development"

# Notes:
# - Versions are pinned intentionally
# - Change via PR only
EOF

  ok ".mise.toml created"
fi

# ---------------------------------------------------------
# .envrc
# ---------------------------------------------------------
if [ -f ".envrc" ]; then
  warn ".envrc already exists. Skipping."
else
  info "Creating .envrc"

  cat > .envrc <<'EOF'
# =========================================================
# direnv activation
# =========================================================

# Load mise (project-local)
eval "$(mise activate bash)"

# Optional: auto-install tools on enter
mise install

# Optional: load local env overrides
if [ -f ".env.local" ]; then
  source .env.local
fi
EOF

  chmod +x .envrc
  ok ".envrc created"
fi

# ---------------------------------------------------------
# Final instructions
# ---------------------------------------------------------
echo
echo "Next steps:"
echo "  1. Review .mise.toml (adjust runtimes if needed)"
echo "  2. Run: direnv allow"
echo "  3. Verify: mise current"
echo
ok "Project runtime initialized"
